// The ONLY place a weekly review is generated outside an explicit signed-in
// user's "Run weekly review" button click. It authenticates with a shared
// secret (never a browser session), only ever acts on the single
// env-configured CRON_USER_ID (never a userId from the request), and still
// runs through the same user-scoped runWeeklyReviewForUser engine every UI
// button uses. It responds to POST only — there is no GET handler, so a
// review can never be generated by a plain browser navigation or a render.
//
// DISABLED by default: with no CRON_SECRET set, every request is rejected
// (401), so the route can never generate a review until the owner turns
// scheduling on. See .github/workflows/weekly-review.yml.example (kept inert
// by its `.example` suffix) and BUILD-PLAN cross-cutting decision #2 —
// scheduling + the Anthropic Batch API are a deferred future step.
//
// This route is listed in PUBLIC_PATHS (src/proxy.ts) so the session-cookie
// proxy doesn't redirect it to /sign-in — the bearer-token check below is the
// real gate; the proxy exemption only lets the request reach it.

import { timingSafeEqual } from "node:crypto";

import { NextResponse } from "next/server";

import { runWeeklyReviewForUser } from "@/lib/reviews/weekly-review-engine";

// Constant-time, length-safe comparison: returns false (never throws) when the
// two strings differ in length, and otherwise compares without leaking timing.
// Never logs either value.
function tokensMatch(a: string, b: string): boolean {
  const aBuf = Buffer.from(a);
  const bBuf = Buffer.from(b);
  if (aBuf.length !== bBuf.length) return false;
  return timingSafeEqual(aBuf, bBuf);
}

export async function POST(request: Request) {
  // 1. Read the bearer token from the Authorization header.
  const auth = request.headers.get("authorization");
  const token = auth?.startsWith("Bearer ") ? auth.slice(7) : null;

  // 2. Reject immediately unless a secret is configured AND the token matches.
  // A single generic "Unauthorized." for every failure — the response never
  // reveals whether the cause was a missing env var or a wrong token, and the
  // secret/token are never logged or placed in the body.
  const secret = process.env.CRON_SECRET;
  if (!secret || !token || !tokensMatch(token, secret)) {
    return NextResponse.json({ error: "Unauthorized." }, { status: 401 });
  }

  // 3. The account to act on comes ONLY from CRON_USER_ID — never from the
  // request. Configured-but-no-target-account is an honest 501, distinct from
  // the 401 auth failure above.
  const userId = process.env.CRON_USER_ID;
  if (!userId) {
    return NextResponse.json(
      { error: "Weekly-review cron is not configured (CRON_USER_ID unset)." },
      { status: 501 },
    );
  }

  // 4. Run the same user-scoped engine the UI button uses.
  const result = await runWeeklyReviewForUser(userId);
  return NextResponse.json(result, { status: result.ok ? 200 : 500 });
}
